### ISSUE TITLE
no base item with id error

### ISSUE THREAD

**Issue by shlnz** [doomeer/kalandralang#1]
Hi,

while creating a recipe for a large cluster jewel, I got the error `Error: no base item with id "Metadata/Items/Jewels/JewelPassiveTreeExpansionMedium"`

Is there no support for clusters, is this a bug or am I doing something wrong? :)
Example recipe:
```buy "Metadata/Items/Jewels/JewelPassiveTreeExpansionMedium" ilvl 84```

**Comment by doomeer** [comment]
Interesting. It looks like cluster jewels are indeed not listed in `base_items.json` from RePoE, but in `cluster_jewels.json` instead, and the format is completely different.

So unfortunately, no, cluster jewels are not supported and there is no immediate workaround, sorry.

**Comment by shlnz** [comment]
Alright, thank you for looking this up. Maybe a feature for the future.
And thanks for writing this cool language 👍  really appreciate it
