### ISSUE TITLE
Harvest Chances for missing crafts

### ISSUE THREAD

**Issue by AR-234** [doomeer/kalandralang#10]
If somebody wants to do the other Harvest crafts, here are the numbers:
 - Reforge more likely has a 90x multiplier
 - Reforge less likely has a 0.01x multiplier
 - Reforge [tag], [tag] more common has a 10x multiplier (Its a guess like fossils)
 - Devine lucky, roll twice keep better one

These numbers are from Craft of Exile.

**Comment by doomeer** [comment]
That will be very useful, thanks!

**Comment by doomeer** [comment]
Quick question though, about "reforge more likely": do you know what is multiplied exactly? My guess would be all mods with the same mod group as mods already on the item, but it could also be by tag instead?

**Comment by AR-234** [comment]
Yes for what I know it is by mod group.

**Comment by AR-234** [comment]
Less likely has a 0.01 multiplier.

Added to main post

**Comment by doomeer** [comment]
I have added more/less likely. Still need to implement more common.

(Divines would require storing mod values which Kalandralang currently doesn't, but maybe later.)

**Comment by doomeer** [comment]
Added reforge more common crafts.

**Comment by AR-234** [comment]
Awesome addition, now only aisling is missing and all the big stuff is taken care off (for base items)

Closed since stuff got implemented
