### ISSUE TITLE
Unveiling can unveil non-unveilable mods

### ISSUE THREAD

**Issue by doomeer** [doomeer/kalandralang#16]
Example: when unveiling a boot prefix, one can get Rin's Cannot be Frozen, which is not supposed to be unveilable (at least not with Aisling and veiled chaos orbs).

To fix this, one needs to find how to restrict the unveil mod pool. The only idea I have right now would be to look at the mod names and only take "Chosen" and "of the Order", but if anyone has a better idea, I'll take it ;)

**Comment by AR-234** [comment]
I compared the data aswell, only thing that really stand out is the name, and maybe this is good..

If "buy" would get the ability to add a veiled rin mod, kalandralang could even unveil that.

**Comment by doomeer** [comment]
I pushed a patch that removes mods other than `Chosen` and `of the Order` from the pool.

Later, allowing to unveil master-specific mods could be interesting but I think most of the time when crafting this is irrelevant.
