### ISSUE TITLE
No SSL or TLS support compiled into Conduit

### ISSUE THREAD

**Issue by FiNEk** [doomeer/kalandralang#2]
Hello! First of all, this is amazing tool you working on :)

But ive encountered this weird problem. I was trying to run `kalandralang write-ninja-costs` and kalandra gave me this error `No SSL or TLS support compiled into Conduit`. Any ideas why it happened?
I had no problems while installing and compiling, and i have no problem running recipes.
My OpenSSL version is 1.1.1l 24 Aug 2021 if that matters at all. Also i can wget any https page from my shell, so i doubt there is something wrong with the system.

I am on Macbook Air M1 (ARM) inside [ocaml/opam:ubuntu docker container](https://hub.docker.com/r/ocaml/opam) (Ubuntu 21.10)
Thats kinda a weird setup, but in theory it should work fine.

**Comment by AR-234** [comment]
opam install ssl
opam install lwt_ssl

did the trick for me, found a forum post were they talk about conduit shifted some dependencies and that was the solution..

**Comment by FiNEk** [comment]
@AR-234 Yep! Worked for me also. Thank you
