### ISSUE TITLE
Item smooshing (Sentinel)

### ISSUE THREAD

**Issue by doomeer** [doomeer/kalandralang#25]
Sentinel brings with it the possibility to take two items and mix them together. Here are some notes I took during the Q&A (that I didn't listen fully to…).

pick one of the two base types, or may choose a new base type that can only be obtained like this

retains all the properties of the core base types:
- corrupted
- implicits
- catalysts

how explicits are chosen:
- puts all mods in the pool
- take a few of them
- can reroll values
- can choose new special mods that can only be obtained like this

influences:
- when mixing two influenced item, the influence of the base that was chosen is kept, the other influence (if any) is lost
- if the item that was not chosen as the base type contains influence mods that cannot spawn with the influence of the selected base type, those mods will not be chosen when mixing

**Comment by nebuchenazarr** [comment]
I took down pretty much the same notes during the stream for CoE. Here's how i think its actually working.

First i would think that the special mods will be in their own modgroup which we will see in the dataset, i would also assume that their weighting will be pretty low compared to the usual weightings.

I would also assume its a pure 50/50 for which item base it keeps. Then it would probably roll for how many affixes spawn from the item with the same probabilities as usual (4-mod 8/12, 5-mod 3/12, 6-mod 1/12). Then roll affixes as usual but within that limited pool which includes the special mods.

I think i heard chris say they could change tiers, or maybe i misheard. If so then i would assume that it puts all tiers of the modifiers that were present in the modpool.

Values being rerolled makes sense since it essentially recreates an item from scratch.

**Comment by AR-234** [comment]
[Actual rules for combining items](https://youtu.be/pfBfrxS9hyI?t=820)
[Combining influenced items](https://youtu.be/pfBfrxS9hyI?t=1480)

**Comment by AR-234** [comment]
> retains all the properties of the core base types:
>     * corrupted
>     * implicits
>     * catalysts

also keeps enchants (taken from the q&a)

> There's also the case of fractured items, is the fractured mod (or mods) garanteed to follow, does that mean you can have 2 frac mod items. I would guess no and yes respectively. But these are guesses.
My guess for the astral plate in the league info page, they used a fractured grasping mail and a fractured astral plate, the base that got picked was the astral plate and the mod that got transfered was the `100% global Defence` mod. atleast from the current info that is available. with 2 fracture mods maybe possible but I guess you summarized it pretty well with:

> One thing is clear though : this will require some community testing to figure out for sure.

**Comment by doomeer** [comment]
Thanks for your inputs nebuchenazarr, that's very useful!

Regarding tiers, my hope is that mods are likely to keep their tiers, as this opens up a lot of possibilities. Otherwise the result would be closer to a kind of harvest reforge more likely.

Overall there are many unknowns:
- what is the weight for mods taken from base items: is it the same as the weight from the regular mod pool? or equiprobable? (hard to design a simple experiment to reach a conclusion here)
- is the regular mod pool present? (easy to prove true: if we get an item with a normal mod that wasn't in the base items, then yes)
- how many mods are taken from base items? is it variable, or more like awakener's orb? (we'll quickly get a rough idea from initial experiments)
- if the same mod is present on both items, does it make it more likely?
- how often do mods keep their tier?
- if they don't keep their tier, do they tend to get a tier which is close to the original one? (a small sample size should give us a rough idea)
- maybe the special mods are actually special tiers of regular mods, kind of like elevated mods? (we may get an idea from datamining)

**Comment by doomeer** [comment]
Thanks for your inputs nebuchenazarr, that's very useful!

Regarding tiers, my hope is that mods are likely to keep their tiers, as this opens up a lot of possibilities. Otherwise the result would be closer to a kind of harvest reforge more likely.

Overall there are many unknowns:
- what is the weight for mods taken from base items: is it the same as the weight from the regular mod pool? or equiprobable? (hard to design a simple experiment to reach a conclusion here)
- is the regular mod pool present? (easy to prove true: if we get an item with a normal mod that wasn't in the base items, then yes)
- how many mods are taken from base items? is it variable, or more like awakener's orb? (we'll quickly get a rough idea from initial experiments)
- if the same mod is present on both items, does it make it more likely?
- how often do mods keep their tier?
- if they don't keep their tier, do they tend to get a tier which is close to the original one? (a small sample size should give us a rough idea)
- maybe the special mods are actually special tiers of regular mods, kind of like elevated mods? (we may get an idea from datamining)
- can fractured mods appear spontaneously or do they need to be fractured in the original item?
- can we obtain two fractured mods? (we can try mixing two fractured items)
- can we obtain two essence mods (something which is not normally possible)? (we can try mixing two essence-crafted items)
- what happens if the base items have a very small number of mods, like zero, or one? (we can try to annul and mix)
- can we mix magic or normal items?
- can we mix corrupted items? (my bet is: no)

Today, it is hard to get three T1 prefixes, but reasonable to get two T2 prefixes. I'm betting that mixing two items with two T1 prefixes each (e.g. two bows essence-crafted with two good elemental damage prefixes) has a good chance of giving three T1 prefixes. Depending on the cost of the new currency used to smoosh items, it may be the more cost effective approach. But they said that the currency was rare.

Is there a place (discord?) where it is likely that players gather their experiment results and try to reverse-engineer how it works?

If you intend to gather data (by mixing items and noting the results), I strongly suggest to explicitly say out loud "I'm going to note this" before each attempt. And then always note the result. If you didn't say this out loud, I strongly suggest to NOT note the result. The reason I say that is that if you don't decide that you will note the result BEFORE the experiment, you may introduce bias, for instance by only noting good or weird results.

**Comment by nebuchenazarr** [comment]
> Is there a place (discord?) where it is likely that players gather their experiment results and try to reverse-engineer how it works?

I often work with people of TfT for experiments such as these. The consensus seems to be that the item recombinators will be quite rare so it will make testing annoying. But lets wait and see.

**Comment by doomeer** [comment]
Some useful info:
- list of recombinator-only mods: https://poedb.tw/us/Recombinator#RecombinatorMods
- a few notes about mechanics: https://poedb.tw/us/Recombinator#CommunityWiki
- Captain Lance's video: www.youtube.com/watch?v=kJYIqwt-0X0

**Comment by doomeer** [comment]
In the JSON files of RePoE, all recombinator mods have identifiers that start with `Recombinator` (and no other mod starts with that). However last time I looked the JSON files do not contain the information of which item type the mods can spawn on. But the list of mods is not very long so worst case it can be hard-coded from the list at poedb.

**Comment by doomeer** [comment]
I can't currently play so I can't experiment in-game, so instead I looked at the 15 crafts of Captain Lance's video. Not only is the sample size from this video very small, but also samples almost entirely consist of items with 4 to 6 mods (with one exception where one item has 3 mods). But it does give an idea. The most obvious result to me is that most of the times, all mods in the resulting item come from the original items (there is only one exception in this sample set).

So far, my conclusions (which are probably obvious) are that the process is probably something like this:
- mods of both items are put in a pool
- a target number of mods is chosen (let's call it T)
- T mods are chosen from the pool
- then an effect can occur, either: upgrade the tier of one mod, downgrade the tier of one mod, add (or replace a mod with?) another completely random mod (which can be a non-recombinator-only mod)
- "mod parity" is not respected: the game doesn't try to choose the same number of mods from item 1 and item 2. Proof: one item got 3 mods from original item number 1, and only 1 from original item number 2. The fact that most of the time parity happens can be explained because once you take a mod, say, from item 1, the pool contains more mods from item 2, etc. so it naturally balances out.

The unknowns:
- how to compute T? It looks like T is greater with more initial mods, but we need a large sample size for each combination of (number of prefixes/suffixes for item 1/2/result) to know the formula exactly. We could assume that T only depends on the total number of mods but this may not be accurate and it's better to count prefixes and suffixes separately for all three items.
- can the effect occur multiple times? (e.g. one mod gets downgraded, another gets upgraded, and a mod is added/replaced by another) here we just need one example where this occurred to know that it can, but it would be nice to get a large sample size to know if the probabilities are independent for each mods or not
- what is the chance to get each effect (looks like about 1/5 to upgrade or downgrade a mod but that is a very rough estimate)
- when a non-recombinator-only mod that was not on the original items appears, is it added, or does it replace an existing mod? Looks like we need a large sample size here to get an idea (we need to estimate probability of T when this effect doesn't happen and then compare this with when the effect does happen; if T is higher when this effect happens, then we can conclude that the mod gets added, else, we can conclude that it replaces an existing mod)

Here is a table with the number of prefixes/suffixes for each case. If you know of a place where a large table like this is being constructed, please let me know :)
```
| #P1 | #S1 | #P2 | #S2 | #P' | #S' | Special                                          |
|-----+-----+-----+-----+-----+-----+--------------------------------------------------|
|   3 |   1 |   3 |   1 |   3 |   1 |                                                  |
|   3 |   0 |   3 |   1 |   3 |   0 | upgraded tier of 1 mod                           |
|   2 |   2 |   3 |   3 |   3 |   2 |                                                  |
|   2 |   2 |   3 |   3 |   3 |   2 |                                                  |
|   1 |   3 |   1 |   3 |   2 |   2 |                                                  |
|   1 |   3 |   1 |   3 |   1 |   3 | upgraded tier of 1 mod (or rerolled value)       |
|   3 |   3 |   2 |   3 |   2 |   2 | no mod parity (more likely because lots of mods) |
|   2 |   2 |   1 |   3 |   2 |   2 | added a new non-recombinator mod                 |
|   2 |   3 |   3 |   1 |   3 |   1 | upgraded tier of 1 mod                           |
|   1 |   3 |   1 |   3 |   1 |   3 |                                                  |
|   2 |   3 |   1 |   3 |   2 |   3 |                                                  |
|   2 |   3 |   2 |   2 |   2 |   2 | downgraded tier of 1 mod                         |
|   2 |   3 |   3 |   2 |   3 |   3 | downgraded tier of 1 mod                         |
|   3 |   3 |   2 |   3 |   3 |   2 | downgraded tier of 1 mod                         |
|   2 |   3 |   2 |   2 |   2 |   3 | downgraded tier of 1 mod                         |
```

**Comment by doomeer** [comment]
Forgot to mention that I implemented partial support for recombinators a couple weeks ago. Partial because it doesn't implement special mods and chance to upgrade / downgrade tiers.

**Comment by doomeer** [comment]
Closing for now because recombinators, while still available in standard, are no longer available in leagues.

If they ever come back, they'll probably work differently anyway.
