### ISSUE TITLE
[Improvement] buy exact/magic item

### ISSUE THREAD

**Issue by haggys22** [doomeer/kalandralang#27]
It is almost impossible to use a magic item like Dictator's Prophecy Wand from the divination cards as a base item. Currently one would need to

- a) scour, then transmute (until exactly the wanted affix)
- b) scour, then transmute/augment (could lead to 2 affixes while the div cards always result in exactly the dictator's prefix)
- c) chaos, then annul (will never result in a magic item)
- d) buy with fractured mod, then scour (results in a fractured item)

All of the above increase the estimated cost by using currency not needed in game. Option d) results in a fractured item which cannot be influenced or lose it's mod when crafting

# Proposal
- Add `exact` keyword. This disables the addition of random modifiers.
- Add `<rarity>` keywords `normal`, `magic` and `rare`. Defaults to the lowest possible rarity if `exact` is given; `rare` otherwise

`buy [<influence>] [<influence>] [exact] [<rarity>] <identifier> [ilvl <number>] [with [fractured] <identifier>]* [for <amount>]`

# Example
The "The Spoiled Prince" divination card can currently be bought for ~15c (x4 for a complete set)

To represent the cost and predictable outcome one could use the following:
```
buy exact magic "Metadata/Items/Weapons/OneHandedWeapons/Wands/Wand16"
  with "LocalIncreasedPhysicalDamagePercentAndAccuracyRating8"
  for 60 chaos
```

**Comment by rbardou** [comment]
Done.

I wanted to do something like this for a while, you gave me the will to actually do it and gave me a nice syntax suggestion, so: thanks ;)

**Comment by doomeer** [comment]
Done.

I wanted to do something like this for a while, you gave me the will to actually do it and gave me a nice syntax suggestion, so: thanks ;)
