### ISSUE TITLE
Beast Imprint and Split Tag, Logic Error

### ISSUE THREAD

**Issue by AR-234** [doomeer/kalandralang#3]
They is a flaw in the imprint logic with the split tag.

Currently it is implemented as split items can't be imprinted.

You can't apply the imprint of an item that got split after, but you can imprint a split item and use that imprint.

**Comment by AR-234** [comment]
Fixed it I think: #5

**Comment by doomeer** [comment]
Oh I was not aware of this! Thanks for the patch, it's now in `master` :+1:
