### ISSUE TITLE
Beast Split can't create normal quality

### ISSUE THREAD

**Issue by AR-234** [doomeer/kalandralang#4]
Currently the beast split can produce normal items, which is not possible.

How it works:
You can't split items with one or less mods.
Both items need atleast one mod. (So atleast magic)

**Comment by doomeer** [comment]
Thanks, I was not aware of this. I pushed a patch to fix this. I hope I got it right this time ;)

**Comment by AR-234** [comment]
awesome will test it and report if something is broken
